<?php
/**
 * Schema.org JSON-LD Structured Data
 *
 * Auto-generated by VoxelSite AEO Engine.
 * Reads from assets/data/site.json and outputs appropriate
 * Schema.org markup for search engines and AI assistants.
 *
 * Include this in _partials/head.php:
 *   <?php if (file_exists(__DIR__ . '/schema.php')) include __DIR__ . '/schema.php'; ?>
 */

$_vxSchemaPath = $_SERVER['DOCUMENT_ROOT'] . '/assets/data/site.json';
if (!file_exists($_vxSchemaPath)) return;

$_vxSite = @json_decode(file_get_contents($_vxSchemaPath), true);
if (!is_array($_vxSite) || empty($_vxSite['name'])) return;

// Map site_type to Schema.org type
$_vxTypeMap = [
    'restaurant'   => 'Restaurant',
    'bakery'       => 'Bakery',
    'cafe'         => 'CafeOrCoffeeShop',
    'bar'          => 'BarOrPub',
    'salon'        => 'BeautySalon',
    'spa'          => 'DaySpa',
    'dentist'      => 'Dentist',
    'doctor'       => 'Physician',
    'clinic'       => 'MedicalClinic',
    'gym'          => 'SportsActivityLocation',
    'fitness'      => 'SportsActivityLocation',
    'hotel'        => 'Hotel',
    'store'        => 'Store',
    'shop'         => 'Store',
    'retail'       => 'Store',
    'agency'       => 'ProfessionalService',
    'consulting'   => 'ProfessionalService',
    'law'          => 'LegalService',
    'legal'        => 'LegalService',
    'accounting'   => 'AccountingService',
    'finance'      => 'FinancialService',
    'education'    => 'EducationalOrganization',
    'school'       => 'School',
    'tutoring'     => 'EducationalOrganization',
    'photography'  => 'ProfessionalService',
    'creative'     => 'ProfessionalService',
    'construction' => 'HomeAndConstructionBusiness',
    'plumbing'     => 'Plumber',
    'electrical'   => 'Electrician',
    'auto'         => 'AutoRepair',
    'mechanic'     => 'AutoRepair',
    'veterinary'   => 'VeterinaryCare',
    'pet'          => 'PetStore',
    'real_estate'  => 'RealEstateAgent',
    'travel'       => 'TravelAgency',
    'tech'         => 'Organization',
    'saas'         => 'Organization',
    'startup'      => 'Organization',
    'nonprofit'    => 'NGO',
    'church'       => 'Church',
    'florist'      => 'Florist',
];

$_vxSchemaType = $_vxTypeMap[$_vxSite['site_type'] ?? ''] ?? 'LocalBusiness';

// Build the schema object
$_vxSchema = [
    '@context' => 'https://schema.org',
    '@type'    => $_vxSchemaType,
    'name'     => $_vxSite['name'],
];

if (!empty($_vxSite['description'])) {
    $_vxSchema['description'] = $_vxSite['description'];
}
if (!empty($_vxSite['url'])) {
    $_vxSchema['url'] = $_vxSite['url'];
}

// Contact info
if (!empty($_vxSite['contact'])) {
    $c = $_vxSite['contact'];

    if (!empty($c['phone'])) {
        $_vxSchema['telephone'] = $c['phone'];
    }
    if (!empty($c['email'])) {
        $_vxSchema['email'] = $c['email'];
    }

    if (!empty($c['address'])) {
        $a = $c['address'];
        $_vxSchema['address'] = [
            '@type'           => 'PostalAddress',
            'streetAddress'   => $a['street'] ?? '',
            'addressLocality' => $a['city'] ?? '',
            'addressRegion'   => $a['region'] ?? '',
            'postalCode'      => $a['postal_code'] ?? '',
            'addressCountry'  => $a['country'] ?? '',
        ];
        // Remove empty address fields
        $_vxSchema['address'] = array_filter($_vxSchema['address'], fn($v) => $v !== '');
        $_vxSchema['address']['@type'] = 'PostalAddress';
    }

    if (!empty($c['coordinates'])) {
        $_vxSchema['geo'] = [
            '@type'     => 'GeoCoordinates',
            'latitude'  => $c['coordinates']['lat'] ?? 0,
            'longitude' => $c['coordinates']['lng'] ?? 0,
        ];
    }
}

// Opening hours
if (!empty($_vxSite['hours']) && is_array($_vxSite['hours'])) {
    $hours = [];
    $dayMap = [
        'Monday' => 'Mo', 'Tuesday' => 'Tu', 'Wednesday' => 'We',
        'Thursday' => 'Th', 'Friday' => 'Fr', 'Saturday' => 'Sa', 'Sunday' => 'Su',
    ];

    foreach ($_vxSite['hours'] as $h) {
        if (!empty($h['closed'])) continue;
        $days = $h['days'] ?? '';
        $open = $h['open'] ?? '09:00';
        $close = $h['close'] ?? '17:00';

        // Convert "Monday-Friday" to "Mo-Fr"
        foreach ($dayMap as $full => $abbr) {
            $days = str_replace($full, $abbr, $days);
        }

        $hours[] = "{$days} {$open}-{$close}";
    }

    if (!empty($hours)) {
        $_vxSchema['openingHours'] = $hours;
    }
}

// Social links (filter out placeholders like '#', 'example.com')
if (!empty($_vxSite['social']) && is_array($_vxSite['social'])) {
    $_vxRealSocial = array_filter($_vxSite['social'], function($u) {
        return is_string($u) && str_starts_with($u, 'http') && $u !== '#' && !str_contains($u, 'example.com');
    });
    if (!empty($_vxRealSocial)) {
        $_vxSchema['sameAs'] = array_values($_vxRealSocial);
    }
}

// Output JSON-LD
echo '<script type="application/ld+json">' . "\n";
echo json_encode($_vxSchema, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE | JSON_PRETTY_PRINT);
echo "\n" . '</script>' . "\n";

// Additional FAQ schema if faq.json exists
$_vxFaqPath = $_SERVER['DOCUMENT_ROOT'] . '/assets/data/faq.json';
if (file_exists($_vxFaqPath)) {
    $_vxFaq = @json_decode(file_get_contents($_vxFaqPath), true);
    $_vxFaqItems = $_vxFaq['questions'] ?? $_vxFaq['faq'] ?? $_vxFaq['items'] ?? $_vxFaq ?? [];

    if (is_array($_vxFaqItems) && !empty($_vxFaqItems)) {
        $faqEntries = [];
        foreach ($_vxFaqItems as $item) {
            if (!is_array($item) || empty($item['question'])) continue;
            $faqEntries[] = [
                '@type'          => 'Question',
                'name'           => $item['question'],
                'acceptedAnswer' => [
                    '@type' => 'Answer',
                    'text'  => $item['answer'] ?? '',
                ],
            ];
        }

        if (!empty($faqEntries)) {
            $faqSchema = [
                '@context'   => 'https://schema.org',
                '@type'      => 'FAQPage',
                'mainEntity' => $faqEntries,
            ];
            echo '<script type="application/ld+json">' . "\n";
            echo json_encode($faqSchema, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE | JSON_PRETTY_PRINT);
            echo "\n" . '</script>' . "\n";
        }
    }
}